[package]
name = "launch-site"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Gear Technologies"]
license = "MIT"

[dependencies]
gstd = { workspace = true, features = ["debug"] }
scale-info = { workspace = true, features = ["derive"] }
parity-scale-codec = { workspace = true, features = ["derive", "full"] }
launch-io.workspace = true

[build-dependencies]
gear-wasm-builder.workspace = true
gmeta.workspace = true
launch-io.workspace = true

[dev-dependencies]
gtest.workspace = true
gclient.workspace = true
tokio.workspace = true
launch-state = { workspace = true, features = ["binary-vendor"] }

[features]
binary-vendor = []

[workspace.dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", features = ["debug"], rev = "78dfa07" }
scale-info = { version = "2", default-features = false, features = ["derive"] }
parity-scale-codec = { version = "3", default-features = false }
launch-io = { path = "io" }
launch-state = { path = "state" }
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", rev = "78dfa07" }
gtest = { git = "https://github.com/gear-tech/gear.git", rev = "78dfa07" }
gclient = { git = "https://github.com/gear-tech/gear.git", rev = "78dfa07" }
tokio = "1"
gmeta = { git = "https://github.com/gear-tech/gear.git", rev = "78dfa07" }

[workspace]
members = ["state"]
